### ISSUE TITLE
go build的时候报错

### ISSUE THREAD

**Issue by nowindnowave** [dbaxg/sqlpump#1]
go: finding github.com/shiena/ansicolor v0.0.0-20151119151921-a422bbe96644
go: finding github.com/golang/protobuf v1.4.2
go: finding google.golang.org/protobuf v1.23.0
go: finding golang.org/x/net v0.0.0-20190620200207-3b0461eec859
go: finding google.golang.org/genproto v0.0.0-20190819201941-24fa4b261c55
go: finding golang.org/x/sys v0.0.0-20200615200032-f1bc736245b1
go: finding golang.org/x/text v0.3.0
# github.com/dbaxg/sqlpump/replace
../../../../pkg/mod/github.com/dbaxg/sqlpump@v0.0.0-20200328145613-bd5b3e00a880/replace/getMeta.go:45:4: impossible type switch case: node.Expr (type sqlparser.SimpleTableExpr) cannot have dynamic type sqlparser.TableName (Format method has pointer receiver)

**Comment by nowindnowave** [comment]
非常遗憾，编译完后执行也还是报错：
{
"resultCode": 1,
"sqlPath": "",
"errorInfo": "exit status 127",
"panicInfo": "",
"stackInfo": "
goroutine 1 [running]:
runtime/debug.Stack(0xc0002fad80, 0xc0003b21a0, 0xf)
	/opt/go/src/runtime/debug/stack.go:24 +0x9f
github.com/dbaxg/sqlpump/log.LogIfError(0xa7fd80, 0xc0002fad80, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/github.com/dbaxg/sqlpump/log/logger.go:55 +0xca
github.com/dbaxg/sqlpump/parse.ParseMapper(0x7ffc744a0679, 0x61, 0xc0002bc090, 0x8a, 0xc000126d00, 0x16, 0xc000126c80, 0x18, 0xc00012ae40, 0x7, ...)
	/usr/local/go/src/github.com/dbaxg/sqlpump/parse/parse.go:286 +0x2ebc
main.main()
	/usr/local/go/src/github.com/dbaxg/sqlpump/cmd/sqlpump.go:68 +0x2db

"
}
